# fly.toml file generated for otog-db on 2022-12-26T19:30:12+07:00

app          = "otog-db"
kill_signal  = "SIGINT"
kill_timeout = 5
processes    = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback        = true

[[services]]
  internal_port = 5432
  protocol      = "tcp"

  [[services.ports]]
    handlers = ["pg_tls"]
    port     = 5432
