# fly.toml file generated for otog-db on 2022-12-25T16:07:54+07:00

app          = "otog-db"
kill_signal  = "SIGINT"
kill_timeout = 5
processes    = []

[build]
  image = "flyio/postgres:14"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback        = true

[[services]]
  http_checks   = []
  internal_port = 5432    # Postgres instance
  processes     = ["app"]
  protocol      = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type       = "connections"

  [[services.ports]]
    handlers = ["pg_tls"]
    port     = 5432

  [[services.tcp_checks]]
    grace_period  = "1s"
    interval      = "15s"
    restart_limit = 0
    timeout       = "2s"
