name: Fly Deploy
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      # - run: flyctl deploy --remote-only --auto-confirm .
      # - run: make IMAGE_VERSION=${{ github.sha }} update
      - run: flyctl deploy --image-label latest --build-only --push --app otog
      - run: flyctl image update --image registry.fly.io/otog:latest --app otog --yes
    
